# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("RDS_HOSTNAME") { "db" } %>
  username: <%= ENV.fetch("RDS_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("RDS_PASSWORD") { "postgres" } %>
  port: <%= ENV.fetch("RDS_PORT") { 5432 } %>

development:
  <<: *default
  database: schrodingers_full_stack_development

test:
  <<: *default
  database: schrodingers_full_stack_test

production:
  <<: *default
  database: <%= ENV.fetch("RDS_DB_NAME") { "schrodingers_full_stack_production" } %>

production_cable:
  <<: *default
  database: <%= ENV.fetch("RDS_DB_NAME") { "schrodingers_full_stack_production" } %>_cable
