# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("PGHOST") { "db" } %>
  password: postgres
  username: postgres

development:
  <<: *default
  database: schrodingers_full_stack_development

test:
  <<: *default
  database: schrodingers_full_stack_test

production:
  primary:
    <<: *default
    database: <%= ENV['RDS_DB_NAME'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    port: <%= ENV['RDS_PORT'] %>
    username: <%= ENV['RDS_USERNAME'] %>
  cache:
    <<: *default
    database: schrodingers_full_stack_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: schrodingers_full_stack_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: schrodingers_full_stack_production_cable
    migrations_paths: db/cable_migrate
